name       : guvcview
homepage   : http://guvcview.sourceforge.net/
version    : 2.0.4
release    : 8
source     :
    - http://downloads.sourceforge.net/project/guvcview/source/guvcview-src-2.0.4.tar.gz : 670ef45168a9b58d36ac42f09c498db5e56b76b0be25b0a6dc97528569334fa2
license    : GPL-2.0
component  : multimedia.video
summary    : Simple GTK interface for capturing and viewing video from devices
description: "Simple GTK interface for capturing and viewing video from devices \n"
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gsl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
