name       : guvcview
version    : 2.0.6
release    : 21
source     :
    - https://downloads.sourceforge.net/project/guvcview/source/guvcview-src-2.0.6.tar.gz : 95381cef5ee139e15f90b79d1425cc22bbaae43f87452cdce6674636aff37e85
homepage   : http://guvcview.sourceforge.net/
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Simple GTK interface for capturing and viewing video from devices
description: |
    Simple GTK interface for capturing and viewing video from devices
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gsl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
