name       : guvcview
homepage   : http://guvcview.sourceforge.net/
version    : 2.0.2
release    : 3
source     :
    - http://downloads.sourceforge.net/project/guvcview/source/guvcview-src-2.0.2.tar.gz : 6478f3f2758bc6dde5c206534f7dcdd8b41fa12545423512bf9ca9d10434ddc2
license    : GPL-2.0
summary    : Simple GTK interface for capturing and viewing video from devices 
clang      : no
description: |
    Simple GTK interface for capturing and viewing video from devices 
builddeps  :
    - pkgconfig(libv4l2)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(gsl)
    - pkgconfig(libpulse)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(alsa)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
