name       : guvcview
homepage   : http://guvcview.sourceforge.net/
version    : 2.0.3
release    : 4
source     :
    - http://downloads.sourceforge.net/project/guvcview/source/guvcview-src-2.0.3.tar.gz : 1f2c79f2dccbf512a0aa1c397ce8e5d37fb0a48008ef72a0d3f10f9dc0758bce
license    : GPL-2.0
summary    : Simple GTK interface for capturing and viewing video from devices 
clang      : no
description: |
    Simple GTK interface for capturing and viewing video from devices 
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gsl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
