name       : guvcview
homepage   : http://guvcview.sourceforge.net/
version    : 2.0.1
release    : 1
source     :
    - http://downloads.sourceforge.net/project/guvcview/source/guvcview-src-2.0.1.tar.gz : dffb86c01bd2e25216d9fbc0c246342246818036d9f63e0488111d757d9b018d
license    : GPL-2.0
summary    : Simple GTK interface for capturing and viewing video from devices 
clang      : no
description: |
    Simple GTK interface for capturing and viewing video from devices 
builddeps  :
    - pkgconfig(libv4l2)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(gsl)
    - pkgconfig(libpulse)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(libavcodec)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
